### ISSUE TITLE
The Package Recipe Holder cannot store the recipe

### ISSUE THREAD

**Issue by SenjumaruShutara** [TheLMiffy1111/PackagedThaumic#3]
The Package Recipe Holder cannot save the Recipe properly after marking the recipe in the Package Recipe Encoder.
PackagedThaumic V1.0.2.7
PackagedAuto V1.0.12.43

**Comment by TheLMiffy1111** [comment]
Please add more info

**Comment by SenjumaruShutara** [comment]
![屏幕截图 2024-03-18 144410](https://github.com/TheLMiffy1111/PackagedThaumic/assets/141470182/a2cccf64-cf49-4786-a35c-d1a726c2f571)

As shown in the picture, after clicking Save, the Package Recipe Holder cannot save the recipe normally.

**Comment by SenjumaruShutara** [comment]
> Please add more info 请补充更多信息

![屏幕截图 2024-03-18 144410](https://github.com/TheLMiffy1111/PackagedThaumic/assets/141470182/05e1333e-4e92-4d4e-a678-68ca5ff60a23)

As shown in the picture, after clicking Save, the Package Recipe Holder cannot save the recipe normally.

**Comment by SenjumaruShutara** [comment]
> > Please add more info 请补充更多信息
> 
> ![屏幕截图 2024-03-18 144410](https://private-user-images.githubusercontent.com/141470182/313575073-05e1333e-4e92-4d4e-a678-68ca5ff60a23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDUwMjAsIm5iZiI6MTcxMDc0NDcyMCwicGF0aCI6Ii8xNDE0NzAxODIvMzEzNTc1MDczLTA1ZTEzMzNlLTRlOTItNGQ0ZS1hNjc4LTY4Y2E1ZmY2MGEyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQwNjUyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MGEyZmJjMDIxNGZjZDJkY2I3NDgxOGZjNzViMjA0MDg5NTQ2MjY5YTA2ODBkNzU0ZGI2ODQyNGQ0OWU5ZGQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qshuL-wLbrItNgkfUCcoLeZSssHtboMf4Cm7_Hu3VFk)
> 
> As shown in the picture, after clicking Save, the Package Recipe Holder cannot save the recipe normally.

![屏幕截图 2024-03-18 144917](https://github.com/TheLMiffy1111/PackagedThaumic/assets/141470182/873aa7c9-9368-4add-a853-dc7345c5bd38)

If it works properly, the Package Recipe Holder should display the recipe name (underlined in red)

**Comment by ghost** [comment]
What modpack are you playing. I'm guessing divine journey (if not check below as well). I checked their CraftTweaker files and found ":" in the recipe ids, you need to remove these for Packaged Thaumic to work properly

**Comment by SenjumaruShutara** [comment]
> What modpack are you playing. I'm guessing divine journey (if not check below as well). I checked their CraftTweaker files and found ":" in the recipe ids, you need to remove these for Packaged Thaumic to work properly

Thank you
