### ISSUE TITLE
Packaged Recipes (especially Infusion) don't mesh well with Primordial Pearls

### ISSUE THREAD

**Issue by Sandman366** [TheLMiffy1111/PackagedThaumic#5]
If an Infusion recipe requires a Primordial Pearl, even if the pearl is at full durability, it will use up the entire pearl. Even if it's not the centerpiece (where an item would replace the pearl). This only an Infusion issue, Arcane Crafting still returns a Pearl at -1 durability.

However, and I'm not sure if this is as plausible, but is it possible to have the encoder recognize "any durability" for Pearls? If I give Infusion _or_ Arcane Crafting a recipe that wants a Primordial Pearl, it will only work with Pearls that match durability exactly. if I try with a recipe that says "use a full Pearl" and then asking it to run with "my only Pearl is half durability", it won't work. Or is that just an AE2 "Processing Pattern" limitation in general?

**Comment by TheLMiffy1111** [comment]
The default behavior of pedestals with partially used items in Packaged Infusion Crafting is to eject the item out into the world, the items should be returned if you connect the pedestals to the ME system
Exact matching pearls are an AE2 limitation, as if I recall correctly AE2 in 1.12 doesn't not allow replacements outside of crafting recipes

**Comment by Sandman366** [comment]
Oh, the _pedestals_ need to be connected? I guess I missed that in the book, I only connected the matrix itself.

Yeah, figured that could end up being the case. Thanks for confirming though.
